ayomi/test_api/Web_App/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LogoutView
from . import views

urlpatterns = [
    
    url('home/', views.home, name='home'),
    url('register/', views.registerPage, name="register"),
	url('login/', views.loginPage, name="login"),  
	url('logout/',LogoutView.as_view(next_page=settings.LOGIN_REDIRECT_URL), name="logout"),
    url('profile/', views.profile, name="profile"),
    url('updateUser/', views.updateUser, name='updateUser'),
]

app_name='Web_App'

ayomi/test_api/test_ayomi/urls.py
from django.contrib import admin
from django.urls import include, path

# from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Web_App.urls')),
] 

ayomi/test_api/Web_App/models.py
from django.db import models

# Create your models here.

ayomi/test_api/Web_App/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

# User form
class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email','first_name', 'last_name', 'password1', 'password2']

ayomi/test_api/Web_App/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout

from django.contrib import messages

from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect

from bootstrap_modal_forms.generic import BSModalCreateView


# Create your views here.
from .models import *
from .forms import CreateUserForm

# Register view
@csrf_protect
def registerPage(request):
	if request.user.is_authenticated:
		return redirect('/home')
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				firstName = form.cleaned_data.get('first_name')
				lastName = form.cleaned_data.get('last_name')
				email = form.cleaned_data.get('email')
				messages.success(request, 'Account was created for ' + firstName + ' ' + lastName)

				return redirect('/login')
			

		context = {'form':form}
		return render(request, 'Web_App/register.html', context)

# Login view
@csrf_protect
def loginPage(request):
	if request.user.is_authenticated:
		return redirect('/profile')
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			firstName = request.POST.get('first_name')
			lastName = request.POST.get('last_name')
			password =request.POST.get('password')
			email =request.POST.get('email')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect('/profile')
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'Web_App/login.html', context)

# Logout view 
@login_required(login_url='login')
def logoutUser(request):
		logout(request)
		return redirect('/login')

# Home view
@login_required(login_url='login')
def home(request):
	context = {}
	return render(request, 'Web_App/home.html', context)

# Profile view
@login_required(login_url='login')
def profile(request):
	context = {}
	return render(request, 'Web_App/profile.html', context)

# Update user view
@login_required(login_url='login')
def updateUser(request, pk):

	# user=User.objects.get(pk=1)
	# form = CreateUserForm(instance=user)

	# if request.method == 'POST':
	# 	form = CreateUserForm(request.POST, instance=user)
	# 	if form.is_valid():
	# 		form.save()
	# 		return redirect('/profile')

	context = {'form':form}
	return render(request, 'Web_App/updateUser.html', context)

ayomi/test_api/Web_App/templates/Web_App/home.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Test AYOMI</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/Web_app/style.css' %}">

</head>
<body>
	{% include 'Web_App/navbar.html' %}
	<div class="container-fluid">
    {% block content %}
    <div class="page-header header-filter" data-parallax="true" style="background-image:url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS52y5aInsxSm31CvHOFHWujqUx_wWTS9iM6s7BAm21oEN_RiGoog');"></div>
	{% endblock %}
    </div>
    <hr>
    <div class="page-header header-filter" data-parallax="true" style="background-image:url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS52y5aInsxSm31CvHOFHWujqUx_wWTS9iM6s7BAm21oEN_RiGoog');"></div>

    <h5> Welcome in our website {{request.user}}</h5>
	
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

ayomi/test_api/Web_App/templates/Web_App/login.html
{% load static %}
<!DOCTYPE html>
<html>
    
<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/Web_app/style.css' %}">

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<button class="btn login_btn" type="submit"> Login</button>
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}			
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'Web_App:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

ayomi/test_api/Web_App/templates/Web_App/navbar.html
{% load static %}

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/Web_app/style.css' %}">
</head>
<nav>
    <div class="container">
        <div class="navbar-translate">
            <a class="btn" href="{% url 'Web_App:home' %}">Home</a>
            {% if user.is_authenticated %}
                <a class="btn" href="{% url 'Web_App:profile' %}"> Hello, {{request.user}}</a>
                <a class="btn" href="{% url 'Web_App:logout' %}">Logout</a>
            {% else %}
                <a class="btn" href="{% url 'Web_App:login' %}">Login</a>
                <a class="btn" href="{% url 'Web_App:register' %}">Register</a>
            {% endif %}   
        </div>    
    </div>
</nav>

ayomi/test_api/Web_App/templates/Web_App/profile.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Test AYOMI</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/Web_app/style.css' %}">

    
</head>
<body>
	{% include 'Web_App/navbar.html' %}
	<div class="container-fluid">
	{% block content %}
	{% endblock %}
    </div>
	<hr>
    <h5 class="text-center"><b>Welcome in your profile </b></h5>
    <br><br><br>

    <div class="container emp-profile">
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <div class="profile-img">
                        <img src="https://www.jamf.com/jamf-nation/img/default-avatars/generic-user-purple.png" class="rounded-circle"/>
                    </div>
                </div>
                <br><br><br>

                <div class="col-md-8"><br>
                    <div class="tab-content profile-tab">
                        <div class="row text-left">
                            <div class="col-md-6">
                                <label><b> Username </b></label>
                            </div>
                            <div class="col-md-6">
                                <p>{{request.user.username}}</p>
                            </div>
                        </div>
                        <div class="row text-left">
                            <div class="col-md-6">
                                <label><b>Full name </b></label>
                            </div>
                            <div class="col-md-6">
                                <p>{{request.user.get_full_name}}</p>
                            </div>
                        </div>
                        <div class="row text-left">
                            <div class="col-md-6">
                                <label><b>Email</b></label>
                            </div>
                            <div class="col-md-6">
                                <p>{{request.user.email}}</p>
                            </div>
                        </div>
                        <div class="row text-left">
                            <div class="col-md-6">
                                <label><b>Last login<b></label>
                            </div>
                            <div class="col-md-6">
                                <p>{{request.user.last_login}}</p>
                            </div>
                        </div>  
                        <br>
                        <div class="row text-left">
                            <div class="col-md-3">
                                <a class="btn btn-primary">Update user</a>
                            </div>  
                        </div>               
                    </div>
                </div>
            </div>     
                
        </form>    
    </div>
    <div class=”bg-modal”>
        <div class=”modal-content”>
        
        </div>
    </div>
<!--  -->
</body>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

ayomi/test_api/Web_App/templates/Web_App/register.html
{% load static %}
<!DOCTYPE html>
<html>
    
<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/Web_app/style.css' %}">
</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
                        </div>
                        <div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.first_name}}
                        </div>
                        <div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.last_name}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>


				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<button class="btn login_btn" type="submit">Register Account</button>
				   		</div>

					</form>
				</div>

				{{form.errors}}
				
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'Web_App:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
        form_fields[2].placeholder='First name..';
        form_fields[3].placeholder='Last name..';
		form_fields[4].placeholder='Email..';
		form_fields[5].placeholder='Enter password...';
		form_fields[6].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

ayomi/test_api/Web_App/templates/Web_App/updateUser.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Test AYOMI</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static '/Web_app/style.css' %}">

        
    </head>
    <body>
        {% include 'Web_App/navbar.html' %}
        <div class="container-fluid">
        {% block content %}
        {% endblock %}
        </div>
        <hr>

        <form method="post" action="">
            {% csrf_token %}
        
        <div class="modal-header">
            <h5 class="modal-title">Update User {{request.user.get_full_name}}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
        
            <div class="modal-body">
                <input type="text" name="email" placeholder="Email..."  value={{request.user.email}} class="form-control">

            </div>
        
            <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="submit-btn btn btn-primary" href="{% url 'Web_App:updateUser' request.user.id  %}">Save</button>
            </div>
        
        </form>
    </body>
</html>